# Generated by Django 4.0.2 on 2022-03-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcode', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('flink', models.TextField()),
            ],
        ),
    ]
