# Generated by Django 4.0.2 on 2022-03-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.CharField(max_length=10)),
                ('command', models.CharField(blank=True, max_length=20)),
                ('command_added', models.BooleanField(default=False)),
                ('last_activity', models.TimeField(auto_now_add=True)),
                ('screenshot', models.TextField()),
                ('website', models.TextField()),
                ('image', models.TextField()),
                ('error_text', models.TextField()),
                ('info', models.TextField()),
            ],
        ),
    ]
