# Generated by Django 4.0.3 on 2022-04-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScamBotMain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bots',
            old_name='error_text',
            new_name='text',
        ),
    ]
